apiVersion: v1
kind: PersistentVolume
metadata: 
  name: server-files-pv
spec: 
  storageClassName: manual
  capacity: 
    storage: 25Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-files-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
